# Rede Neural Multicamadas (MPL)
Uma rede MPL é uma classe de rede neural artificial *feedforward* (ANN). Um MLP consiste em pelo menos três camadas de nós: uma camada de entrada , uma camada oculta e uma camada de saída . Exceto para os nós de entrada, cada nó é um neurônio que usa uma função de ativação não linear . O MPL utiliza uma técnica de aprendizado supervisionado chamada *backpropagation* para treinamento.



### Implementando uma RNA multicamadas

A imagem a seguir mostra a nossa rede, com as unidades de entrada marcadas como Input1, Input2 e Input3 (**Input Layer**) conectadas com os *nós* da camada oculta (**Hidden Layer**). Por sua vez as saída dos *nós* da camada oculda servem como entrada para os *nós*  da camada de saída (**Output Layer**). <img src='MPL.png' /><br>

<p style="text-align:center">  <i> Diagrama de uma MPL</i> </p>
 

Lembrando que em cada *nó* temos: 

$$f(h) = sigmoid(h)=\frac 1 {1+e^{-h}}$$  

onde

<p style="text-align:center"> $$h = \frac 1n\sum_{i=1}^n(w_i*x_i)+b$$  </p>




    



## Configuração da MPL

In [1]:
#Importando a biblioteca
import numpy as np

#Função do cáculo da sigmóide
def sigmoid(x):
    return 1/(1+np.exp(-x))

#Arquitetura da MPL
N_input = 3
N_hidden = 5
N_output = 4

#Vetor dos valores de entrada
x = np.array([0.1, 0.2, -0.6])
target =np.array([0.7, 0.2])
learnrate = 0.5

#Pesos da Camada Oculta

weights_input_hidden = np.array([[-0.07,  0.06, -0.05, 0.03],
                              [ 0.06,  0.10,  0.07, 0.02],
                              [-0.07,  0.04, -0.02, 0.01]])

#Pesos da Camada de Saída
weights_hidden_output = np.array([[-0.18,  0.11],
                               [-0.08,  0.05],
                               [-0.04,  0.07],
                               [-0.03,  0.07]])



### Forward Pass

In [2]:
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)

output = sigmoid(output_layer_in)

print('As saídas da rede são',output)


As saídas da rede são [0.45825438 0.537853  ]


## Backward Pass

In [3]:
error = target - output

output_error_term = error * output * (1 - output)

hidden_error = np.dot(weights_hidden_output,output_error_term)

hidden_error_term = hidden_error * hidden_layer_output * (1 - hidden_layer_output)

delta_w_h_o = learnrate * output_error_term*hidden_layer_output[:, None]
print('delta_w_h_o: ',delta_w_h_o)

delta_w_i_h = learnrate * hidden_error_term * x[:, None]
print('delta_w_i_h: ',delta_w_i_h)



delta_w_h_o:  [[ 0.0153563  -0.02148808]
 [ 0.01501878 -0.02101578]
 [ 0.01516131 -0.02121523]
 [ 0.01501128 -0.02100529]]
delta_w_i_h:  [[-2.50367059e-04 -1.12501976e-04 -1.03477911e-04 -9.59874061e-05]
 [-5.00734118e-04 -2.25003951e-04 -2.06955821e-04 -1.91974812e-04]
 [ 1.50220235e-03  6.75011853e-04  6.20867464e-04  5.75924437e-04]]


### Atualização dos Pesos

In [4]:
weights_input_hidden = learnrate * delta_w_i_h
print('weights_input_hidden: ',weights_input_hidden)
weights_hidden_output = learnrate * delta_w_h_o
print('weights_hidden_output: ',weights_hidden_output)

weights_input_hidden:  [[-1.25183529e-04 -5.62509878e-05 -5.17389553e-05 -4.79937031e-05]
 [-2.50367059e-04 -1.12501976e-04 -1.03477911e-04 -9.59874061e-05]
 [ 7.51101176e-04  3.37505927e-04  3.10433732e-04  2.87962218e-04]]
weights_hidden_output:  [[ 0.00767815 -0.01074404]
 [ 0.00750939 -0.01050789]
 [ 0.00758066 -0.01060761]
 [ 0.00750564 -0.01050264]]
